export const atomTypes = {
"ainf": {desc: "Asset information to identify, license and play", standart: "DECE"},
"avcn": {desc: "AVC NAL Unit Storage Box", standart: "DECE"},
"bloc": {desc: "Base location and purchase location for license acquisition", standart: "DECE"},
"bpcc": {desc: "Bits per component", standart: "JPEG2000"},
"buff": {desc: "Buffering information", standart: "NALu Video"},
"bxml": {desc: "binary XML container", standart: "ISO"},
"ccid": {desc: "OMA DRM Content ID", standart: "OMA DRM 2.1"},
"cdef": {desc: "type and ordering of the components within the codestream", standart: "JPEG2000"},
"clip": {desc: "Reserved", standart: "ISO"},
"cmap": {desc: "mapping between a palette and codestream components", standart: "JPEG2000"},
"co64": {desc: "64-bit chunk offset", standart: "ISO"},
"coin": {desc: "Content Information Box", standart: "DECE"},
"colr": {desc: "specifies the colourspace of the image", standart: "JPEG2000"},
"crgn": {desc: "Reserved", standart: "ISO"},
"crhd": {desc: "reserved for ClockReferenceStream header", standart: "MP4v1"},
"cslg": {desc: "composition to decode timeline mapping", standart: "ISO"},
"ctab": {desc: "Reserved", standart: "ISO"},
"ctts": {desc: "(composition) time to sample", standart: "ISO"},
"cvru": {desc: "OMA DRM Cover URI", standart: "OMA DRM 2.1"},
"dinf": {desc: "data information box, container", standart: "ISO"},
"dref": {desc: "data reference box, declares source(s) of media data in track", standart: "ISO"},
"dsgd": {desc: "DVB Sample Group Description Box", standart: "DVB"},
"dstg": {desc: "DVB Sample to Group Box", standart: "DVB"},
"edts": {desc: "edit list container", standart: "ISO"},
"elst": {desc: "an edit list", standart: "ISO"},
"emsg": {desc: "event message", standart: "DASH"},
"evti": {desc: "Event information", standart: "ATSC 3.0"},
"fdel": {desc: "File delivery information (item info extension)", standart: "ISO"},
"feci": {desc: "FEC Informatiom", standart: "ISO"},
"fecr": {desc: "FEC Reservoir", standart: "ISO"},
"fiin": {desc: "FD Item Information", standart: "ISO"},
"fire": {desc: "File Reservoir", standart: "ISO"},
"fpar": {desc: "File Partition", standart: "ISO"},
"frma": {desc: "original format box", standart: "ISO"},
"free": {desc: "free space", standart: "ISO"},
"ftyp": {desc: "file type and compatibility", standart: "ISO"},
"gitn": {desc: "Group ID to name", standart: "ISO"},
"grpi": {desc: "OMA DRM Group ID", standart: "OMA DRM 2.0"},
"hdlr": {desc: "handler, declares the media (handler) type", standart: "ISO"},
"hmhd": {desc: "hint media header, overall information (hint track only)", standart: "ISO"},
"hpix": {desc: "Hipix Rich Picture (user-data or meta-data)", standart: "Hipix"},
"icnu": {desc: "OMA DRM Icon URI", standart: "OMA DRM 2.0"},
"ID32": {desc: "ID3 version 2 container", standart: "id3v2"},
"idat": {desc: "Item data", standart: "ISO"},
"ihdr": {desc: "Image Header", standart: "JPEG2000"},
"iinf": {desc: "item information", standart: "ISO"},
"iloc": {desc: "item location", standart: "ISO"},
"imap": {desc: "Reserved", standart: "ISO"},
"imif": {desc: "IPMP Information box", standart: "ISO"},
"infe": {desc: "Item information entry", standart: "ISO"},
"infu": {desc: "OMA DRM Info URL", standart: "OMA DRM 2.0"},
"iods": {desc: "Object Descriptor container box", standart: "MP4v1"},
"iphd": {desc: "reserved for IPMP Stream header", standart: "MP4v1"},
"ipmc": {desc: "IPMP Control Box", standart: "ISO"},
"ipro": {desc: "item protection", standart: "ISO"},
"iref": {desc: "Item reference", standart: "ISO"},
"jP  ": {desc: "JPEG 2000 Signature", standart: "JPEG2000"},
"jp2c": {desc: "JPEG 2000 contiguous codestream", standart: "JPEG2000"},
"jp2h": {desc: "Header", standart: "JPEG2000"},
"jp2i": {desc: "intellectual property information", standart: "JPEG2000"},
"kmat": {desc: "Reserved", standart: "ISO"},
"leva": {desc: "Leval assignment", standart: "ISO"},
"load": {desc: "Reserved", standart: "ISO"},
"loop": {desc: "Looping behavior", standart: "WhatsApp"},
"lrcu": {desc: "OMA DRM Lyrics URI", standart: "OMA DRM 2.1"},
"m7hd": {desc: "reserved for MPEG7Stream header", standart: "MP4v1"},
"matt": {desc: "Reserved", standart: "ISO"},
"mdat": {desc: "The atom which contains the raw frame and audio data can be identified by it’s atom type string, which in this case is mdat (short for media data)", standart: "ISO"},
"mdhd": {desc: "media header, overall information about the media", standart: "ISO"},
"mdia": {desc: "container for the media information in a track", standart: "ISO"},
"mdri": {desc: "Mutable DRM information", standart: "OMA DRM 2.0"},
"meco": {desc: "additional metadata container", standart: "ISO"},
"mehd": {desc: "movie extends header box", standart: "ISO"},
"mere": {desc: "metabox relation", standart: "ISO"},
"meta": {desc: "Metadata container", standart: "ISO"},
"mfhd": {desc: "movie fragment header", standart: "ISO"},
"mfra": {desc: "Movie fragment random access", standart: "ISO"},
"mfro": {desc: "Movie fragment random access offset", standart: "ISO"},
"minf": {desc: "media information container", standart: "ISO"},
"mjhd": {desc: "reserved for MPEG-J Stream header", standart: "MP4v1"},
"moof": {desc: "movie fragment", standart: "ISO"},
"moov": {desc: "container for all the meta-data", standart: "ISO"},
"mvcg": {desc: "Multiview group", standart: "NALu Video"},
"mvci": {desc: "Multiview Information", standart: "NALu Video"},
"mvex": {desc: "movie extends box", standart: "ISO"},
"mvhd": {desc: "movie header, overall declarations", standart: "ISO"},
"mvra": {desc: "Multiview Relation Attribute", standart: "NALu Video"},
"nmhd": {desc: "Null media header, overall information (some tracks only)", standart: "ISO"},
"ochd": {desc: "reserved for ObjectContentInfoStream header", standart: "MP4v1"},
"odaf": {desc: "OMA DRM Access Unit Format", standart: "OMA DRM 2.0"},
"odda": {desc: "OMA DRM Content Object", standart: "OMA DRM 2.0"},
"odhd": {desc: "reserved for ObjectDescriptorStream header", standart: "MP4v1"},
"odhe": {desc: "OMA DRM Discrete Media Headers", standart: "OMA DRM 2.0"},
"odrb": {desc: "OMA DRM Rights Object", standart: "OMA DRM 2.0"},
"odrm": {desc: "OMA DRM Container", standart: "OMA DRM 2.0"},
"odtt": {desc: "OMA DRM Transaction Tracking", standart: "OMA DRM 2.0"},
"ohdr": {desc: "OMA DRM Common headers", standart: "OMA DRM 2.0"},
"padb": {desc: "sample padding bits", standart: "ISO"},
"paen": {desc: "Partition Entry", standart: "ISO"},
"pclr": {desc: "palette which maps a single component in index space to a multiple- component image", standart: "JPEG2000"},
"pdin": {desc: "Progressive download information", standart: "ISO"},
"pitm": {desc: "primary item reference", standart: "ISO"},
"pnot": {desc: "Reserved", standart: "ISO"},
"prft": {desc: "Producer reference time", standart: "ISO"},
"pssh": {desc: "Protection system specific header", standart: "ISO Common Encryption"},
"res ": {desc: "grid resolution", standart: "JPEG2000"},
"resc": {desc: "grid resolution at which the image was captured", standart: "JPEG2000"},
"resd": {desc: "default grid resolution at which the image should be displayed", standart: "JPEG2000"},
"rinf": {desc: "restricted scheme information box", standart: "ISO"},
"saio": {desc: "Sample auxiliary information offsets", standart: "ISO"},
"saiz": {desc: "Sample auxiliary information sizes", standart: "ISO"},
"sbgp": {desc: "Sample to Group box", standart: "ISO"},
"schi": {desc: "scheme information box", standart: "ISO"},
"schm": {desc: "scheme type box", standart: "ISO"},
"sdep": {desc: "Sample dependency", standart: "NALu Video"},
"sdhd": {desc: "reserved for SceneDescriptionStream header", standart: "MP4v1"},
"sdtp": {desc: "Independent and Disposable Samples Box", standart: "ISO"},
"sdvp": {desc: "SD Profile Box", standart: "SDV"},
"segr": {desc: "file delivery session group", standart: "ISO"},
"senc": {desc: "Sample specific encryption data", standart: "ISO Common Encryption"},
"sgpd": {desc: "Sample group definition box", standart: "ISO"},
"sidx": {desc: "Segment Index Box", standart: "3GPP"},
"sinf": {desc: "protection scheme information box", standart: "ISO"},
"skip": {desc: "free space", standart: "ISO"},
"smhd": {desc: "sound media header, overall information (sound track only)", standart: "ISO"},
"srmb": {desc: "System Renewability Message", standart: "DVB"},
"srmc": {desc: "System Renewability Message container", standart: "DVB"},
"srpp": {desc: "STRP Process", standart: "ISO"},
"ssix": {desc: "Sub-sample index", standart: "ISO"},
"stbl": {desc: "sample table box, container for the time/space map", standart: "ISO"},
"stco": {desc: "chunk offset, partial data-offset information", standart: "ISO"},
"stdp": {desc: "sample degradation priority", standart: "ISO"},
"sthd": {desc: "Subtitle Media Header Box", standart: "ISO"},
"strd": {desc: "Sub-track definition", standart: "ISO"},
"stri": {desc: "Sub-track information", standart: "ISO"},
"stsc": {desc: "sample-to-chunk, partial data-offset information", standart: "ISO"},
"stsd": {desc: "sample descriptions (codec types, initialization etc.)", standart: "ISO"},
"stsg": {desc: "Sub-track sample grouping", standart: "ISO"},
"stsh": {desc: "shadow sync sample table", standart: "ISO"},
"stss": {desc: "sync sample table (random access points)", standart: "ISO"},
"stsz": {desc: "sample sizes (framing)", standart: "ISO"},
"stts": {desc: "(decoding) time-to-sample", standart: "ISO"},
"styp": {desc: "Segment Type Box", standart: "3GPP"},
"stz2": {desc: "compact sample sizes (framing)", standart: "ISO"},
"subs": {desc: "Sub-sample information", standart: "ISO"},
"swtc": {desc: "Multiview Group Relation", standart: "NALu Video"},
"tfad": {desc: "Track fragment adjustment box", standart: "3GPP"},
"tfdt": {desc: "Track fragment decode time", standart: "ISO"},
"tfhd": {desc: "Track fragment header", standart: "ISO"},
"tfma": {desc: "Track fragment media adjustment box", standart: "3GPP"},
"tfra": {desc: "Track fragment radom access", standart: "ISO"},
"tibr": {desc: "Tier Bit rate", standart: "NALu Video"},
"tiri": {desc: "Tier Information", standart: "NALu Video"},
"tkhd": {desc: "Track header, overall information about the track", standart: "ISO"},
"traf": {desc: "Track fragment", standart: "ISO"},
"trak": {desc: "container for an individual track or stream", standart: "ISO"},
"tref": {desc: "track reference container", standart: "ISO"},
"trex": {desc: "track extends defaults", standart: "ISO"},
"trgr": {desc: "Track grouping information", standart: "ISO"},
"trik": {desc: "Facilitates random access and trick play modes", standart: "DECE"},
"trun": {desc: "track fragment run", standart: "ISO"},
"udta": {desc: "user-data", standart: "ISO"},
"uinf": {desc: "a tool by which a vendor may provide access to additional information associated with a UUID", standart: "JPEG2000"},
"UITS": {desc: "Unique Identifier Technology Solution", standart: "Universal Music Group"},
"ulst": {desc: "a list of UUID’s", standart: "JPEG2000"},
"url ": {desc: "a URL", standart: "JPEG2000"},
"uuid": {desc: "user-extension box", standart: "ISO"},
"vmhd": {desc: "video media header, overall information (video track only)", standart: "ISO"},
"vwdi": {desc: "Multiview Scene Information", standart: "NALu Video"},
"xml ": {desc: "XML container", standart: "ISO"},
"albm": {desc: "Album title and track number for media", standart: "3GPP"},
"alou": {desc: "Album loudness base", standart: "ISO"},
"angl": {desc: "Name of the camera angle through which the clip was shot", standart: "Apple"},
"auth": {desc: "Author of the media", standart: "3GPP"},
"clfn": {desc: "Name of the clip file", standart: "Apple"},
"clid": {desc: "Identifier of the clip", standart: "Apple"},
"clsf": {desc: "Classification of the media", standart: "3GPP"},
"cmid": {desc: "Identifier of the camera", standart: "Apple"},
"cmnm": {desc: "Name that identifies the camera", standart: "Apple"},
"coll": {desc: "Name of the collection from which the media comes", standart: "3GPP"},
"cprt": {desc: "copyright etc.", standart: "ISO"},
"date": {desc: "Date and time, formatted according to ISO 8601, when the content was created. For clips captured by recording devices, this is typically the date and time when the clip’s recording started.", standart: "Apple"},
"dscp": {desc: "Media description", standart: "3GPP"},
"gnre": {desc: "Media genre", standart: "3GPP"},
"hinf": {desc: "hint information", standart: "ISO"},
"hnti": {desc: "Hint information", standart: "ISO"},
"kywd": {desc: "Media keywords", standart: "3GPP"},
"loci": {desc: "Media location information", standart: "3GPP"},
"ludt": {desc: "Track loudness container", standart: "ISO"},
"manu": {desc: "Manufacturer name of the camera", standart: "Apple"},
"modl": {desc: "Model name of the camera", standart: "Apple"},
"orie": {desc: "Orientation information", standart: "3GPP"},
"perf": {desc: "Media performer name", standart: "3GPP"},
"reel": {desc: "Name of the tape reel", standart: "Apple"},
"rtng": {desc: "Media rating", standart: "3GPP"},
"scen": {desc: "Name of the scene for which the clip was shot", standart: "Apple"},
"shot": {desc: "Name that identifies the shot", standart: "Apple"},
"slno": {desc: "Serial number of the camera", standart: "Apple"},
"strk": {desc: "Sub track information", standart: "ISO"},
"thmb": {desc: "Thumbnail image of the media", standart: "3GPP"},
"titl": {desc: "Media title", standart: "3GPP"},
"tlou": {desc: "Track loudness base", standart: "ISO"},
"tsel": {desc: "Track selection", standart: "ISO"},
"urat": {desc: "User 'star' rating of the media", standart: "3GPP"},
"yrrc": {desc: "Year when media was recorded", standart: "3GPP"},
"dcfD": {desc: "Marlin DCF Duration, user-data atom type", standart: "OMArlin"},
"elng": {desc: "Extended Language Tag", standart: "QT"},
"wide": {desc: "Expansion space reservation", standart: "QT"}
};